spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.26.137.179:3306/webpj?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    web: